##
##  k8s-sample -- Kubernetes Sample Application
##  Copyright (c) 2019 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Distributed under MIT license <https://spdx.org/licenses/MIT.html>
##

---
{{- if .Values.app.storage.shared }}
#   persistent volume claim (application tier)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: {{ .Values.ns.name }}
    name: {{ .Values.app.name }}
    labels:
        app: {{ .Values.id }}
spec:
    accessModes:
        - ReadWriteMany
    volumeMode: Filesystem
    storageClassName: {{ .Values.app.storage.type }}
    resources:
        requests:
            storage: {{ .Values.app.storage.size }}
{{- end }}

---
{{- if .Values.db.enabled }}
{{- if .Values.db.storage.shared }}
#   persistent volume claim (database tier)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: {{ .Values.ns.name }}
    name: {{ .Values.db.name }}
    labels:
        app: {{ .Values.id }}
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    storageClassName: {{ .Values.db.storage.type }}
    resources:
        requests:
            storage: {{ .Values.db.storage.size }}
{{- end }}
{{- end }}

