##
##  k8s-sample -- Kubernetes Sample Application
##  Copyright (c) 2019 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Distributed under MIT license <https://spdx.org/licenses/MIT.html>
##

---
{{- if .Values.app.service.url }}
#   traffic ingress for service
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    namespace: {{ .Values.ns.name }}
    name: {{ .Values.app.name }}
    labels:
        app: {{ .Values.id }}
        tier: app
    annotations:
        traefik.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        {{- if .Values.app.service.host }}
        -   host: {{ .Values.app.service.host }}
            http:
        {{- else }}
        -   http:
        {{- end }}
                paths:
                    -   path: {{ default "/" .Values.app.service.url }}
                        backend:
                            serviceName: {{ .Values.app.name }}
                            servicePort: {{ .Values.app.service.port }}
{{- end }}

