##
##  Sample -- Sample Application
##  Copyright (c) 2019 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Distributed under MIT license <https://spdx.org/licenses/MIT.html>
##

---
#   namespace
apiVersion: v1
kind: Namespace
metadata:
    name: {{ .Values.ns.name }}
    labels:
        app: {{ .Values.id }}

