##
##  Sample -- Sample Application
##  Copyright (c) 2019 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Distributed under MIT license <https://spdx.org/licenses/MIT.html>
##

---
#   service account in namespace
apiVersion: v1
kind: ServiceAccount
metadata:
    namespace: {{ .Values.ns.name }}
    name: {{ .Values.ns.account }}
    labels:
        app: {{ .Values.id }}

---
#   full-access role for service account in namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: {{ .Values.ns.name }}
    name: {{ .Values.ns.account }}
    labels:
        app: {{ .Values.id }}
rules:
    -   apiGroups: [ "", "*" ]
        resources: [ "*" ]
        verbs: [ "*" ]

---
#   binding of full-access role to service account in namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    namespace: {{ .Values.ns.name }}
    name: {{ .Values.ns.account }}
    labels:
        app: {{ .Values.id }}
subjects:
    -   kind: ServiceAccount
        namespace: {{ .Values.ns.name }}
        name: {{ .Values.ns.account }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ .Values.ns.account }}

