##
##  Sample -- Sample Application
##  Copyright (c) 2019 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Distributed under MIT license <https://spdx.org/licenses/MIT.html>
##

---
#   service for pods
apiVersion: v1
kind: Service
metadata:
    namespace: {{ .Values.ns.name }}
    name: {{ .Values.app.name }}
    labels:
        app: {{ .Values.id }}
        tier: app
spec:
    type: ClusterIP
    selector:
        app: {{ .Values.id }}
        tier: app
    ports:
        -   protocol: {{ .Values.app.service.type }}
            port: {{ .Values.app.service.port }}
            targetPort: default

---
{{- if .Values.db.enabled }}
#   service for pods
apiVersion: v1
kind: Service
metadata:
    namespace: {{ .Values.ns.name }}
    name: {{ .Values.db.name }}
    labels:
        app: {{ .Values.id }}
        tier: db
spec:
    type: ClusterIP
    selector:
        app: {{ .Values.id }}
        tier: db
    ports:
        -   protocol: {{ .Values.db.service.type }}
            port: {{ .Values.db.service.port }}
            targetPort: default
{{- end }}

