##
##  k8s-sample -- Kubernetes Sample Application
##  Copyright (c) 2019-2020 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Distributed under MIT license <https://spdx.org/licenses/MIT.html>
##

package:
    namespace:        null
    name:             null
    fullname:         null

app:
    name:             app
    image:
        name:         "docker.io/engelschall/k8s-sample"
        tag:          "0.9.2-20200106"
    container:
        replicas:     1
        restart:      Always
        args:
            default:  [ "-d", "sqlite3:/data/app.sqlite" ]
            db:       [ "-d", "pg:postgres://app:app@k8s-sample-db:5432/app", "-w", "10" ]
        env:
    service:
        type:         TCP
        port:         9090
        url:          /k8s-sample
    storage:
        path:         /data
        type:         nfs
        size:         100Mi
        shared:       false

db:
    enabled:          false
    name:             db
    image:
        name:         "docker.msg.team/ps/std-postgresql"
        tag:          "12.1-20191229"
    container:
        replicas:     1
        restart:      Always
        args:         []
        env:
            CFG_ADMIN_PASSWORD:  postgresql
            CFG_ADMIN_USERNAME:  postgresql
            CFG_CUSTOM_DATABASE: app
            CFG_CUSTOM_PASSWORD: app
            CFG_CUSTOM_USERNAME: app
    service:
        type:         TCP
        port:         5432
    storage:
        path:         /data
        type:         nfs
        size:         100Mi
        shared:       false

